services:
  selenium-chrome:
    image: selenium/standalone-chrome:131.0
    container_name: selenium-chrome
    ports:
      - "4444:4444" # Porta para WebDriver
      - "7900:7900" # Porta para VNC
    shm_size: "2g" # Memória compartilhada para evitar erros de memória no navegador
    restart: unless-stopped
    environment:
      - SE_VNC_PASSWORD="Inform18@"
      - SE_VNC_VIEW_ONLY=true
      - SE_SESSION_TIMEOUT=0 # Desabilitar timeout das sessões
      - SE_SESSION_REQUEST_TIMEOUT=0 # Desabilitar timeout na fila de sessões
      - SE_NODE_MAX_SESSIONS=1 # Apenas 1 sessão por contêiner para evitar conflitos
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true # Permitir mais sessões se necessário
      - SE_START_XVFB=true # Necessário para novos modos headless
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=false # Desabilitar limpeza automática de processos do navegador
      - SE_SESSION_RETRY_INTERVAL=5 # Evita erros em sessões intermitentes
      - SE_GRID_TIMEOUT=300000 # Timeout para requests longos

