services:
  selenium-chrome:
    image: selenium/standalone-chrome:131.0
    container_name: selenium-chrome
    ports:
      - "4444:4444" # Porta para WebDriver
      - "7900:7900" # Porta para VNC
    shm_size: "2g" # Memória compartilhada para evitar erros de memória no navegador
    restart: unless-stopped
    environment:
      - SE_VNC_PASSWORD=Inform18@
      - SE_VNC_VIEW_ONLY=true
      - SE_SESSION_TIMEOUT=0 # Desabilitar timeout das sessões
      - SE_SESSION_REQUEST_TIMEOUT=300 # Tempo para aguardar antes de desistir de uma sessão
      - SE_NODE_MAX_SESSIONS=1 # Apenas 1 sessão por contêiner
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true # Permitir múltiplas sessões (se necessário)
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=false # Não remove processos de navegadores inativos automaticamente
      - SE_SESSION_RETRY_INTERVAL=5 # Tenta reconectar a sessão em caso de erro
      - SE_NODE_SESSION_TIMEOUT=0 # Timeout para sessões inativas
      - SE_GRID_TIMEOUT=300000 # Timeout para requests longos
      - SE_ENABLE_HEARTBEAT=true # Ativa heartbeat para manter a sessão viva

